package modelo;
// Generated 28-abr-2024 16:05:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private String isbn;
     private Autor autor;
     private Categoria categoria;
     private Editorial editorial;
     private Idioma idioma;
     private Recurso recurso;
     private String titulo;
     private String descripcion;
     private Date fecha;
     private int cantidad;

    public Libro() {
    }

    public Libro(String isbn, Autor autor, Categoria categoria, Editorial editorial, Idioma idioma, Recurso recurso, String titulo, String descripcion, Date fecha, int cantidad) {
       this.isbn = isbn;
       this.autor = autor;
       this.categoria = categoria;
       this.editorial = editorial;
       this.idioma = idioma;
       this.recurso = recurso;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.cantidad = cantidad;
    }
   
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public Autor getAutor() {
        return this.autor;
    }
    
    public void setAutor(Autor autor) {
        this.autor = autor;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Editorial getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(Editorial editorial) {
        this.editorial = editorial;
    }
    public Idioma getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(Idioma idioma) {
        this.idioma = idioma;
    }
    public Recurso getRecurso() {
        return this.recurso;
    }
    
    public void setRecurso(Recurso recurso) {
        this.recurso = recurso;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


