package modelo;
// Generated 28-abr-2024 16:05:02 by Hibernate Tools 4.3.1



/**
 * Ordenador generated by hbm2java
 */
public class Ordenador  implements java.io.Serializable {


     private String nombre;
     private Recurso recurso;

    public Ordenador() {
    }

    public Ordenador(String nombre, Recurso recurso) {
       this.nombre = nombre;
       this.recurso = recurso;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Recurso getRecurso() {
        return this.recurso;
    }
    
    public void setRecurso(Recurso recurso) {
        this.recurso = recurso;
    }




}


