package modelo;
// Generated 28-abr-2024 16:05:02 by Hibernate Tools 4.3.1



/**
 * Portatil generated by hbm2java
 */
public class Portatil  implements java.io.Serializable {
    

     private String numSerie;
     private Recurso recurso;
     private SistemaOperativo sistemaOperativo;
     private String marca;
     private String modelo;

    public Portatil() {
    }

    public Portatil(String numSerie, Recurso recurso, SistemaOperativo sistemaOperativo, String marca, String modelo) {
       this.numSerie = numSerie;
       this.recurso = recurso;
       this.sistemaOperativo = sistemaOperativo;
       this.marca = marca;
       this.modelo = modelo;
    }
   
    public String getNumSerie() {
        return this.numSerie;
    }
    
    public void setNumSerie(String numSerie) {
        this.numSerie = numSerie;
    }
    public Recurso getRecurso() {
        return this.recurso;
    }
    
    public void setRecurso(Recurso recurso) {
        this.recurso = recurso;
    }
    public SistemaOperativo getSistemaOperativo() {
        return this.sistemaOperativo;
    }
    
    public void setSistemaOperativo(SistemaOperativo sistemaOperativo) {
        this.sistemaOperativo = sistemaOperativo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }




}


