package modelo;
// Generated 28-abr-2024 16:05:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Recurso generated by hbm2java
 */
public class Recurso  implements java.io.Serializable {


     private Integer id;
     private boolean disponible;
     private Set libros = new HashSet(0);
     private Set salas = new HashSet(0);
     private Set reservas = new HashSet(0);
     private Set portatils = new HashSet(0);
     private Set ordenadors = new HashSet(0);
     private Set refuerzos = new HashSet(0);

    public Recurso() {
    }

	
    public Recurso(boolean disponible) {
        this.disponible = disponible;
    }
    public Recurso(boolean disponible, Set libros, Set salas, Set reservas, Set portatils, Set ordenadors, Set refuerzos) {
       this.disponible = disponible;
       this.libros = libros;
       this.salas = salas;
       this.reservas = reservas;
       this.portatils = portatils;
       this.ordenadors = ordenadors;
       this.refuerzos = refuerzos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public boolean isDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(boolean disponible) {
        this.disponible = disponible;
    }
    public Set getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set libros) {
        this.libros = libros;
    }
    public Set getSalas() {
        return this.salas;
    }
    
    public void setSalas(Set salas) {
        this.salas = salas;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }
    public Set getPortatils() {
        return this.portatils;
    }
    
    public void setPortatils(Set portatils) {
        this.portatils = portatils;
    }
    public Set getOrdenadors() {
        return this.ordenadors;
    }
    
    public void setOrdenadors(Set ordenadors) {
        this.ordenadors = ordenadors;
    }
    public Set getRefuerzos() {
        return this.refuerzos;
    }
    
    public void setRefuerzos(Set refuerzos) {
        this.refuerzos = refuerzos;
    }




}


