package modelo;
// Generated 28-abr-2024 16:05:02 by Hibernate Tools 4.3.1



/**
 * Refuerzo generated by hbm2java
 */
public class Refuerzo  implements java.io.Serializable {


     private Integer id;
     private Recurso recurso;
     private Sala sala;
     private Usuario usuario;
     private String descripcion;
     private String asignatura;
     private String tipo;

    public Refuerzo() {
    }

    public Refuerzo(Recurso recurso, Sala sala, Usuario usuario, String descripcion, String asignatura, String tipo) {
       this.recurso = recurso;
       this.sala = sala;
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.asignatura = asignatura;
       this.tipo = tipo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Recurso getRecurso() {
        return this.recurso;
    }
    
    public void setRecurso(Recurso recurso) {
        this.recurso = recurso;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(String asignatura) {
        this.asignatura = asignatura;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


