package modelo;
// Generated 28-abr-2024 16:05:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {

     private Integer id;
     private Recurso recurso;
     private Usuario usuario;
     private Date fecha;
     private double duracionHoras;
     private boolean entregado;

    public Reserva() {
    }

    public Reserva(Recurso recurso, Usuario usuario, Date fecha, double duracionHoras, boolean entregado) {
       this.recurso = recurso;
       this.usuario = usuario;
       this.fecha = fecha;
       this.duracionHoras = duracionHoras;
       this.entregado = entregado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Recurso getRecurso() {
        return this.recurso;
    }
    
    public void setRecurso(Recurso recurso) {
        this.recurso = recurso;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getDuracionHoras() {
        return this.duracionHoras;
    }
    
    public void setDuracionHoras(double duracionHoras) {
        this.duracionHoras = duracionHoras;
    }
    public boolean isEntregado() {
        return this.entregado;
    }
    
    public void setEntregado(boolean entregado) {
        this.entregado = entregado;
    }

}


