package modelo;
// Generated 28-abr-2024 16:05:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private String nombre;
     private Recurso recurso;
     private int aforo;
     private Set refuerzos = new HashSet(0);

    public Sala() {
    }

	
    public Sala(String nombre, Recurso recurso, int aforo) {
        this.nombre = nombre;
        this.recurso = recurso;
        this.aforo = aforo;
    }
    public Sala(String nombre, Recurso recurso, int aforo, Set refuerzos) {
       this.nombre = nombre;
       this.recurso = recurso;
       this.aforo = aforo;
       this.refuerzos = refuerzos;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Recurso getRecurso() {
        return this.recurso;
    }
    
    public void setRecurso(Recurso recurso) {
        this.recurso = recurso;
    }
    public int getAforo() {
        return this.aforo;
    }
    
    public void setAforo(int aforo) {
        this.aforo = aforo;
    }
    public Set getRefuerzos() {
        return this.refuerzos;
    }
    
    public void setRefuerzos(Set refuerzos) {
        this.refuerzos = refuerzos;
    }




}


